const $=id=>document.getElementById(id);
const definitions=[{name:'ハッピーアタック',type:'ノーマル',css:'',pp:15,power:29,description:'気分を上げて攻撃'},{name:'ダンシングビート',type:'かくとう',css:'fight',pp:10,power:39,description:'ダンスで強く攻撃'},{name:'トロピカルウェーブ',type:'みず',css:'water',pp:10,power:34,description:'波で攻撃'},{name:'リラックスタイム',type:'ノーマル',css:'',pp:5,power:0,description:'HPを45回復'}];
let state,epoch=0,sound=false,audio;
function tone(freq=440){if(!sound)return;try{audio??=new(window.AudioContext||window.webkitAudioContext)();audio.resume();let o=audio.createOscillator(),g=audio.createGain();o.type='square';o.frequency.value=freq;g.gain.setValueAtTime(.035,audio.currentTime);g.gain.exponentialRampToValueAtTime(.001,audio.currentTime+.15);o.connect(g);g.connect(audio.destination);o.start();o.stop(audio.currentTime+.16)}catch{}}
function render(){for(const side of ['player','enemy']){let amount=state[side]/180*100;$(side+'-bar').style.width=amount+'%';$(side+'-bar').style.background=amount>50?'#59cc79':amount>20?'#efc74f':'#e16a59'}$('hp').textContent=state.player+' / 180';$('turn').textContent='TURN '+String(state.turn).padStart(2,'0');$('moves').replaceChildren();definitions.forEach((m,i)=>{let b=document.createElement('button');b.className='move';b.disabled=state.busy||state.over||state.pp[i]===0;b.setAttribute('aria-label',m.name+'、'+m.description+'、残りPP '+state.pp[i]);b.innerHTML='<span class="move-name">'+m.name+'</span><span class="move-meta"><span class="type '+m.css+'">'+m.type+'</span><span>PP '+state.pp[i]+' / '+m.pp+'</span></span>';b.onclick=()=>turn(i);$('moves').append(b)});$('moves').hidden=state.over;$('retry').hidden=!state.over}
function say(text,label){$('message').textContent=text;if(label)$('phase').textContent=label}
function reset(){epoch++;state={player:180,enemy:180,pp:definitions.map(m=>m.pp),turn:1,busy:false,over:false};$('enemy').classList.remove('faint');$('player').classList.remove('faint');$('effect').className='';say('やせいの マタサブロウが あらわれた！ マタサブロウは どうする？','YOUR TURN');render()}
const delay=ms=>new Promise(r=>setTimeout(r,ms));
function animate(id,cls){$(id).classList.remove(cls);void $(id).offsetWidth;$(id).classList.add(cls);setTimeout(()=>$(id).classList.remove(cls),600)}
function finish(won){state.over=true;state.busy=false;$(won?'enemy':'player').classList.add('faint');say(won?'やせいの マタサブロウを たおした！ 最高のバカンスだ！':'マタサブロウは たおれた…。ひと休みして、もう一度！',won?'YOU WIN!':'BATTLE OVER');tone(won?880:160);render();$('retry').focus()}
async function turn(i){if(state.busy||state.over||!state.pp[i])return;const ticket=epoch,m=definitions[i];state.busy=true;state.pp[i]--;render();say('マタサブロウの '+m.name+'！','YOUR MOVE');tone(m.power?520:740);animate('player',m.power?'attack':'heal');await delay(650);if(ticket!==epoch)return;if(m.power){const damage=m.power+Math.floor(Math.random()*8);state.enemy=Math.max(0,state.enemy-damage);animate('enemy','hit');if(m.css)animate('effect',m.css==='water'?'water-effect':'fight-effect');say('やせいの マタサブロウに '+damage+' ダメージ！')}else{let n=Math.min(45,180-state.player);state.player+=n;say(n?'リラックスして HPが '+n+' かいふくした！':'HPは まんたんだ！')}render();await delay(950);if(ticket!==epoch)return;if(!state.enemy){finish(true);return}const opponent=definitions[(state.turn-1)%3];say('やせいの マタサブロウの '+opponent.name+'！','ENEMY TURN');animate('enemy','attack');tone(260);await delay(650);if(ticket!==epoch)return;const damage=23+Math.floor(Math.random()*12);state.player=Math.max(0,state.player-damage);animate('player','hit');say('マタサブロウは '+damage+' ダメージを うけた！');render();await delay(850);if(ticket!==epoch)return;if(!state.player){finish(false);return}state.turn++;state.busy=false;if(state.pp.every(p=>p===0)){state.pp=definitions.map(m=>m.pp);say('ひと息ついて PPが かいふくした！ つぎの技は？','YOUR TURN')}else say('マタサブロウは どうする？','YOUR TURN');render()}
$('sound').onclick=()=>{sound=!sound;$('sound').textContent='♪ サウンド '+(sound?'ON':'OFF');$('sound').setAttribute('aria-pressed',String(sound));tone()};$('retry').onclick=reset;$('reset').onclick=reset;reset();
